# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170829_2120'),
    ]

    operations = [
    ]
