# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
    ]
