# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170906_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 9, 6, 21, 6, 2, 851676))),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_views', to='catalog.Book')),
            ],
            options={
                'verbose_name_plural': 'Entry Views',
            },
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
